# Generated by Django 5.2.4 on 2025-07-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_play_image"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="theatrehall",
            table="theatre_hall",
        ),
    ]
